export const mockSources = [
  {
    id: "mvtd-23-boat",
    title: "MVTD Test Sequence 23-Boat",
    description: "Public maritime tracking sequence assembled locally from MVTD dataset frames.",
    source_page:
      "https://huggingface.co/datasets/AhsanBB/Maritime_Visual_Tracking_Dataset_MVTD/tree/main/test/23-Boat",
    download_url:
      "https://huggingface.co/datasets/AhsanBB/Maritime_Visual_Tracking_Dataset_MVTD/tree/main/test/23-Boat",
    local_path: "/backend/data/inputs/mvtd-23-boat.mp4",
    exists_locally: true,
    license_name: "CC0-1.0",
  },
  {
    id: "pexels-coastal-traffic",
    title: "Pexels Coastal Boat Traffic",
    description: "Demo maritime clip with lateral vessel motion and shoreline background.",
    source_page: "https://www.pexels.com/search/videos/boat%20sea/",
    download_url:
      "https://videos.pexels.com/video-files/17842168/17842168-hd_1920_1080_30fps.mp4",
    local_path: "/backend/data/inputs/pexels-coastal-traffic.mp4",
    exists_locally: false,
    license_name: "Pexels License",
  },
  {
    id: "pexels-channel-transit",
    title: "Pexels Channel Transit",
    description: "Alternative clip to compare tracker behavior with different vessel framing.",
    source_page: "https://www.pexels.com/search/videos/boat%20sea/",
    download_url:
      "https://videos.pexels.com/video-files/32078691/13679072_1080_1920_25fps.mp4",
    local_path: "/backend/data/inputs/pexels-channel-transit.mp4",
    exists_locally: false,
    license_name: "Pexels License",
  },
];

export const mockRun = {
  run_id: "demo-run-offline",
  status: "completed",
  created_at: "2026-06-22T10:20:00Z",
  updated_at: "2026-06-22T10:24:00Z",
  source_id: "mvtd-23-boat",
  output_label: "offline-preview",
  progress: 1,
  controls: {
    confidence_threshold: 0.55,
    detection_interval: 4,
    max_track_age: 12,
    min_box_area: 900,
    process_scale: 0.8,
    alert_area_ratio: 0.025,
    motion_weight: 0.35,
    glare_suppression: 0.45,
    sharpen_strength: 0.35,
    temporal_smoothing: 0.2,
    disturbance_profile: "mixed",
    enable_clahe: true,
    enable_glare_mask: true,
    enable_temporal_smoothing: true,
    comparison_view: true,
  },
  summary: {
    frames_processed: 764,
    video_fps: 30,
    processed_fps: 11.2,
    total_detections: 184,
    unique_tracks: 5,
    active_alerts: 2,
    disturbance_profile: "mixed",
    device: "cuda",
    notes: [
      "Hybrid pipeline combines model and motion cues.",
      "Left pane shows disturbed imagery; right pane shows recovered detections.",
      "Alerting is driven by persistence and apparent target growth.",
    ],
  },
  artifacts: {
    input_video: "",
    output_video: "",
    preview_image: "",
    timeline_json: "",
  },
  alerts: [
    {
      frame_index: 128,
      timestamp_seconds: 4.27,
      track_id: 2,
      severity: "warning",
      message: "Track 2 flagged as watch.",
    },
    {
      frame_index: 341,
      timestamp_seconds: 11.36,
      track_id: 4,
      severity: "critical",
      message: "Track 4 flagged as critical.",
    },
  ],
  latest_tracks: [
    {
      track_id: 2,
      label: "boat",
      confidence: 0.81,
      bbox: [894, 318, 1042, 412],
      age: 52,
      misses: 0,
      source: "model",
      alert_state: "watch",
      last_seen_seconds: 25.3,
    },
    {
      track_id: 4,
      label: "candidate-boat",
      confidence: 0.42,
      bbox: [1158, 340, 1298, 448],
      age: 16,
      misses: 1,
      source: "motion",
      alert_state: "critical",
      last_seen_seconds: 25.3,
    },
  ],
};

export const mockTimeline = [
  { frame_index: 0, timestamp_seconds: 0.0, track_count: 0, alerts: [] },
  { frame_index: 90, timestamp_seconds: 3.0, track_count: 1, alerts: [] },
  { frame_index: 180, timestamp_seconds: 6.0, track_count: 2, alerts: [] },
  { frame_index: 270, timestamp_seconds: 9.0, track_count: 3, alerts: [] },
  {
    frame_index: 360,
    timestamp_seconds: 12.0,
    track_count: 4,
    alerts: [{ severity: "critical", message: "Track 4 flagged as critical." }],
  },
  { frame_index: 450, timestamp_seconds: 15.0, track_count: 3, alerts: [] },
  { frame_index: 540, timestamp_seconds: 18.0, track_count: 2, alerts: [] },
];
